MyFavourite = ['Tokyo','HongKong','IceLand','ShangHai','Waterloo']
print(MyFavourite)
print(sorted(MyFavourite))
print(MyFavourite)
print(sorted(MyFavourite,reverse = True))
print(MyFavourite)
MyFavourite.reverse()
print(MyFavourite)
MyFavourite.reverse()
print(MyFavourite)
MyFavourite.sort()
print(MyFavourite)
MyFavourite.sort(reverse = True)
print(MyFavourite)
